apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bop-customer-api
  namespace: application
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm-charts
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: helm-chart
        namespace: flux-system
      interval: 1m
  values:
    fullnameOverride: bop-customer-api
    image:
      tag: 1.16.0
    autoscalingPolicy:
      minReplicas: 1
      maxReplicas: 2
      targetCpuUtilization: 50

    serviceHealth:
      readinessProbe:
        port: 8080
        healthEndpoint: /
        failureThreshold: 3
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 2
      livenessProbe:
        port: 8080
        healthEndpoint: /
        failureThreshold: 3
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 2

    resources:
      limits:
        memory: 128Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 50m
 
    # -- Configmap for Service
    configMap:
      SALESTAXSERVICE: 'net.tcp://88888888888888'
      SHARED: shared
      APPLICATION__ENVIRONMENT: devqa
