apiVersion: v1
kind: ConfigMap
metadata:
    name: bop-config-ui-values
    namespace: application
data:
  values.yaml: |
    fullnameOverride: bop-config-ui
    image.tag: 1.16.0

    serviceHealth:
      readinessProbe:
        httpGet:
          path: /
          port: http
      livenessProbe:
        httpGet:
          path: /
          port: http

   

