apiVersion: v1
kind: ConfigMap
metadata:
    name: bop-config-api-values
    namespace: application
data:
  values.yaml: |
    fullnameOverride: bop-config-api
    image.tag: 1.16.0

    autoscalingPolicy:
      minReplicas: 1
      maxReplicas: 2
      targetCpuUtilization: 50

    serviceHealth:
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 5
        timeoutSeconds: 1
        port: 8081
        healthEndpoint: /admin/health
      livenessProbe:
        initialDelaySeconds: 30 # Must be greater than app startup time
        periodSeconds: 5
        timeoutSeconds: 1
        port: 8081
        healthEndpoint: /admin/health

    resources:
      limits:
        memory: 128Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 50m
 
    # -- Configmap for Service
    configMap:
      SALESTAXSERVICE: 'net.tcp://1123123123'
      SHARED: shared
      APPLICATION__ENVIRONMENT: devqa
