apiVersion: v1
kind: ConfigMap
metadata:
    name: bop-config-ui-values
    namespace: application
data:
  values.yaml: |-
    foo: bar
    fullnameOverride: bop-config-api
    image.tag: "1.16.0"

   

