apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bop-config-api
  namespace: application
spec:
  interval: 1m
  chart:
    spec:
      chart: application/base/helm-charts
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m

#---
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

#resources:
#  - bop-config-api.yaml